namespace blog_generator.Configs;

public class PathManagementConfig
{
    public string BlogFolder {get;set;} = "";
    public string StylesFolder {get;set;} = "";

    /// <summary>
    /// The root location for dynamically generated content (blogs, styles, etc)
    /// </summary>
    /// <value></value>
    public string LocalContentRoot {get;set;} = "";

    /// <summary>
    /// The root web url for dynamically generated content (blogs, styles, etc)
    /// </summary>
    /// <value></value>
    public string WebContentRoot {get;set;} = "";

    /// <summary>
    /// The root location for static files, such as markup and other files included in the blog service but 
    /// not generated by us.
    /// </summary>
    /// <value></value>
    public string WebStaticRoot {get;set;} = "";
}